name: Release Draft

on:
  push:
    branches:
      - release/*

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}